---
- name: Update APT package cache
  action: apt update_cache=yes

- name: Run apt-get upgrade
  action: apt upgrade=yes

- name: Install vim incase i ever need to manually edit anything (I know i shouldn't)
  action: apt pkg=vim state=installed

- name: Install fail2ban to prevent brute force attacks 
  action: apt pkg=fail2ban state=installed

- name: Install unattended-upgrades
  action: apt pkg=unattended-upgrades state=present

- name: Adjust APT update intervals
  action: copy src=apt_periodic dest=/etc/apt/apt.conf.d/10periodic

- name: Make sure unattended-upgrades only installs from $ubuntu_release-security
  action: lineinfile dest=/etc/apt/apt.conf.d/50unattended-upgrades regexp="$ubuntu_release-updates" state=absent
